//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace ParticipantsAPI.Entity
{
    public partial class Participant
    {
        public string Email { get; set; }
        public string Mobilenumber { get; set; }
        public string MobileNumber { get; internal set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Pincode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public string E_q { get; set; }
        public string Tpwd { get; set; }
    }
    public class AddParticipantOutput
    {
        public string Message { get; set; }
        public HttpStatusCode RespCode { get; set; }
        public string Email { get; set; }
        public string Mobilenumber { get; set; }
        public string MobileNumber { get; internal set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Pincode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public string E_q { get; set; }
        public string Tpwd { get; set; }
    }
    public class UpdateParticipantOutput
    {
        public HttpStatusCode RespCode { get; set; }
        public string Message { get; set; }
       
    }
    public class AddParticipantInput
    {
        public string Email { get; set; }
        public string MobileNumber { get; set; }
       
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Pincode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public string E_q { get; set; }
        public string Tpwd { get; set; }
    }
    public class UpdateParticipantInput
    {
        public string Email { get; set; }
        public string Mobilenumber { get; set; }
        public string MobileNumber { get; internal set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Pincode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public string E_q { get; set; }
        public string Tpwd { get; set; }
    }
    public class GetParticipantInput
    {
        public string Email { get; set; }
    }
    public class CheckParticipantInput
    {
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

